### ISSUE TITLE
Build failed.

### ISSUE THREAD

**Issue by ghost** [Alexmitter/osu-lazer-linux-installer#10]
MSBUILD : error MSB1011: Specify which project or solution file to use because this folder contains more than one project or solution file.
Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1011: Specify which project or solution file to use because this folder contains more than one project or solution file.

**Comment by Alexmitter** [comment]
Please try one of the 3 choices in the Stable category, do you experience the same issue there?

**Comment by Diegomastro** [comment]
I get the exact same error using each of the in Stable and the one in Daily.
I don't know if it's useful for you to know but I'm runnning ubuntu 18.04 and it's the first time I try to install osu! in this pc, and I ran first "Install Dependencies" option

**Comment by Alexmitter** [comment]
Fixed by @phoenixmcallister, thanks to him.
