### ISSUE TITLE
Outdated .NET dependencies

### ISSUE THREAD

**Issue by developomp** [Alexmitter/osu-lazer-linux-installer#15]
[Instruction in the wiki](https://github.com/Alexmitter/osu-lazer-linux-installer/wiki/Full-Instructions-English) says that the installer requires .NET Core SDK 2.2 but in the [download page](https://dotnet.microsoft.com/download/dotnet-core) SDK 2.2 has met its EOL.
And even in the [osu GitHub page](https://github.com/ppy/osu#developing-or-debugging) it says that it requires SDK 3.1 or higher.

**Comment by Alexmitter** [comment]
Could you please refer me to the point in wiki were the 2.2 SDK is mentioned?
I see "dotnet core sdk 3.1 libgbm-dev" in general dependencies.

**Comment by developomp** [comment]
https://github.com/Alexmitter/osu-lazer-linux-installer/wiki/Full-Instructions-English

![22](https://user-images.githubusercontent.com/40858122/81271744-78ce6b80-9087-11ea-8d97-0f9426ded3cc.png)

**Comment by Alexmitter** [comment]
How did I miss that... Anyways thank you.
I will go through all the wiki pages when I integrate the appimage build support. Then the dependencies will only be needed for those who choose to compile.
